### ISSUE TITLE
Crash when attempting to call hud_change

### ISSUE THREAD

**Issue by fluxionary** [MultiCraft/MultiCraft2#37]
##### Minetest version

```
MultiCraft 2.0.0 (Linux)
Using Irrlicht 1.8.5
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### Summary
Calling `player:hud_change(hud_id, stat, value)` crashes the server when `value` is not a number. This does not reflect the behavior of minetest nor the multicraft documentation. See https://github.com/entuland/rhotator/issues/5 for an example of this causing problems in practice. The bug seems to be in here:
https://github.com/MultiCraft/MultiCraft2/blob/bb25210dd00e522b1dc141115a22a916aaa31c6e/src/script/common/c_content.cpp#L1997-L2065

Compare https://github.com/minetest/minetest/blob/258ae994915e1b9fc5b3a72627886f2ce4334902/src/script/common/c_content.cpp#L2007-L2082

##### Steps to reproduce

Install the version of the rhotator that was mentioned, and click on a few things with it.

**Comment by luk3yx** [comment]
This seems to be caused by attempting to call `player:hud_change("hud_elem_type", "text")`. The `read_hud_change` code hasn't been modified in MultiCraft itself so I assume this error would also happen in MT 5.4.1 (which MultiCraft 2 is currently based on). Minetest 5.5.0 should warn about trying to change `hud_elem_type` with hud_change.

I suggest not calling hud_change the `hud_elem_type` value, replacing the loop in hud_update with the below code seems to fix this issue:

```lua
	for key, value in pairs(def) do
		if key ~= "hud_elem_type" then
			player:hud_change(hud_id, key, value)
		end
	end
```

**Comment by fluxionary** [comment]
This does indeed seem to be the correct way to do things. Thanks!
